name: forecast_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  jiffy: ^6.3.2
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/icons/01d.png
    - assets/icons/02d.png
    - assets/icons/03d.png
    - assets/icons/04d.png
    - assets/icons/6.png
    - assets/icons/7.png
    - assets/icons/09d.png
    - assets/icons/10d.png
    - assets/icons/11d.png
    - assets/icons/13d.png
    - assets/icons/39.png
    - assets/icons/50d.png
    - assets/icons/weather.png





  uses-material-design: true